# Generated by Django 2.2.6 on 2019-10-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StkRemains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nQty', models.BigIntegerField(verbose_name='Количество')),
                ('idGood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.GdsGood')),
            ],
        ),
    ]
