# Generated by Django 2.2.6 on 2019-10-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StkAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_create_date', models.DateTimeField(verbose_name='Дата содания')),
                ('d_reg_date', models.DateTimeField(verbose_name='Дата проведения')),
                ('n_direction', models.SmallIntegerField(verbose_name='Направление')),
                ('s_state', models.CharField(choices=[('100', 'Оформляется'), ('300', 'Выполнен')], max_length=3, verbose_name='Состояние')),
            ],
        ),
        migrations.AlterField(
            model_name='stkremains',
            name='idGood',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.GdsGood', verbose_name='Тмц'),
        ),
        migrations.CreateModel(
            name='StkActDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_order', models.IntegerField(verbose_name='Номер')),
                ('n_qty', models.BigIntegerField(verbose_name='Количество')),
                ('id_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StkAct', verbose_name='Накладная')),
                ('id_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц')),
            ],
        ),
    ]
