# Generated by Django 2.2.6 on 2019-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20191007_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkact',
            name='d_create_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата содания'),
        ),
    ]
