# Generated by Django 2.2.6 on 2019-11-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20191104_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkact',
            name='s_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
