# Generated by Django 2.2.6 on 2021-10-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_gdsgoodremainslevel'),
        ('trd', '0009_auto_20211009_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_external_id', models.CharField(max_length=256, verbose_name='Идентификатор во внешней системе')),
            ],
            options={
                'verbose_name': 'Сопоставление товаров',
                'verbose_name_plural': 'Сопоставления товаров',
            },
        ),
        migrations.CreateModel(
            name='IntgCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_caption', models.CharField(max_length=256, verbose_name='Наименование')),
                ('s_type', models.CharField(choices=[('Ebay', 'Ebay')], max_length=256, verbose_name='Тип интеграции')),
                ('s_config', models.TextField(verbose_name='Конфигурация')),
                ('id_trade_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trd.TrdTradeSystem')),
            ],
            options={
                'verbose_name': 'Контур интеграции',
                'verbose_name_plural': 'Контуры интеграции',
            },
        ),
        migrations.CreateModel(
            name='GoodMappingDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_qty', models.BigIntegerField(verbose_name='Количество')),
                ('id_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц')),
                ('id_good_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intg.GoodMapping', verbose_name='Меппинг товара')),
            ],
            options={
                'verbose_name': 'Позиция меппинга товаров',
                'verbose_name_plural': 'Позиции меппинга товаров',
            },
        ),
        migrations.AddField(
            model_name='goodmapping',
            name='id_circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intg.IntgCircuit'),
        ),
    ]
