# Generated by Django 2.2.6 on 2021-10-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trd', '0009_auto_20211009_2337'),
        ('intg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmapping',
            name='id_circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intg.IntgCircuit', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='intgcircuit',
            name='id_trade_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trd.TrdTradeSystem', verbose_name='Торговая система'),
        ),
        migrations.CreateModel(
            name='IntgCircuitRunTimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_json_data', models.TextField(verbose_name='Json-данные')),
                ('id_circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intg.IntgCircuit', verbose_name='Контур')),
            ],
            options={
                'verbose_name': 'Данные интеграции',
                'verbose_name_plural': 'Данные интеграции',
            },
        ),
        migrations.CreateModel(
            name='DeliverySystemMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_external_id', models.CharField(max_length=256, verbose_name='Идентификатор во внешней системе')),
                ('id_circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intg.IntgCircuit', verbose_name='Контур')),
                ('id_delivery_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trd.TrdDeliveryService', verbose_name='Служба доставки')),
            ],
            options={
                'verbose_name': 'Сопоставление службы доставки',
                'verbose_name_plural': 'Сопоставления службы доставки',
            },
        ),
    ]
