# Generated by Django 2.2.6 on 2021-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intg', '0003_auto_20211010_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmappingdet',
            name='n_qty',
            field=models.BigIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
