# Generated by Django 2.2.6 on 2019-11-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MnfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCaption', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'ordering': ['sCaption'],
            },
        ),
        migrations.CreateModel(
            name='MnfItemDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_qty', models.PositiveIntegerField(blank=True, verbose_name='Количество')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnf.MnfItem', verbose_name='Объект производства')),
            ],
        ),
    ]
