# Generated by Django 2.2.6 on 2019-11-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('mnf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MnfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCaption', models.CharField(max_length=200, verbose_name='Наименование')),
                ('id_good', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц')),
            ],
            options={
                'ordering': ['sCaption'],
            },
        ),
        migrations.AddField(
            model_name='mnfitemdet',
            name='id_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mnf.MnfMaterial', verbose_name='Материал'),
        ),
    ]
