# Generated by Django 2.2.6 on 2019-11-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnf', '0002_auto_20191103_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mnfitem',
            options={'ordering': ['sCaption'], 'verbose_name': 'Объект производства', 'verbose_name_plural': 'Объекты производства'},
        ),
        migrations.AlterModelOptions(
            name='mnfitemdet',
            options={'verbose_name': 'Состав объекта производства', 'verbose_name_plural': 'Составы объекта производства'},
        ),
        migrations.AlterModelOptions(
            name='mnfmaterial',
            options={'ordering': ['s_caption'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.RenameField(
            model_name='mnfmaterial',
            old_name='sCaption',
            new_name='s_caption',
        ),
    ]
