# Generated by Django 2.2.6 on 2019-11-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnf', '0003_auto_20191104_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnfmaterial',
            name='id_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц'),
        ),
        migrations.AlterUniqueTogether(
            name='mnfitemdet',
            unique_together={('id_item', 'id_material')},
        ),
    ]
