# Generated by Django 2.2.6 on 2019-11-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stkact_s_desc'),
        ('mnf', '0004_auto_20191104_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MnfShiftResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_create_date', models.DateTimeField(db_index=True, verbose_name='Дата содания')),
                ('d_reg_date', models.DateTimeField(null=True, verbose_name='Дата проведения')),
                ('s_state', models.CharField(choices=[('100', 'Оформляется'), ('300', 'Выполнен')], max_length=3, verbose_name='Состояние')),
                ('id_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.StkAct', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Отчет о выполненной работе',
                'verbose_name_plural': 'Отчеты о выполненной работе',
            },
        ),
        migrations.CreateModel(
            name='MnfShiftResultMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('id_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mnf.MnfMaterial', verbose_name='Материал')),
                ('id_shift_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnf.MnfShiftResult', verbose_name='Отчет о выполненной работе')),
            ],
            options={
                'verbose_name': 'Дополнительный материал',
                'verbose_name_plural': 'Дополнительные материалы',
                'unique_together': {('id_shift_result', 'id_material')},
            },
        ),
        migrations.CreateModel(
            name='MnfShiftResultItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mnf.MnfItem', verbose_name='Объект производства')),
                ('id_shift_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnf.MnfShiftResult', verbose_name='Отчет о выполненной работе')),
            ],
            options={
                'verbose_name': 'Произведенный объект',
                'verbose_name_plural': 'Произведенные объекты',
                'unique_together': {('id_shift_result', 'id_item')},
            },
        ),
    ]
