# Generated by Django 2.2.6 on 2019-11-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnf', '0005_mnfshiftresult_mnfshiftresultitems_mnfshiftresultmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MnfRemainsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_caption', models.CharField(max_length=200, verbose_name='Наименование')),
                ('s_color', models.CharField(max_length=200, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Уровень остатков',
                'verbose_name_plural': 'Уровени остатков',
                'ordering': ['s_caption'],
            },
        ),
        migrations.RemoveField(
            model_name='mnfshiftresult',
            name='d_reg_date',
        ),
        migrations.CreateModel(
            name='MnfMaterialRemainsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_from', models.PositiveIntegerField(blank=True, verbose_name='Количество от')),
                ('n_to', models.PositiveIntegerField(blank=True, verbose_name='Количество от')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mnf.MnfRemainsLevel', verbose_name='Уровень')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnf.MnfMaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Уровень остатков материала',
                'verbose_name_plural': 'Уровни остатков материала',
                'unique_together': {('id_material', 'id_level')},
            },
        ),
    ]
