# Generated by Django 2.2.6 on 2019-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnf', '0006_auto_20191129_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mnfremainslevel',
            options={'ordering': ['s_caption'], 'verbose_name': 'Уровень остатков', 'verbose_name_plural': 'Уровни остатков'},
        ),
        migrations.AlterField(
            model_name='mnfmaterialremainslevel',
            name='n_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество от'),
        ),
        migrations.AlterField(
            model_name='mnfmaterialremainslevel',
            name='n_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество от'),
        ),
    ]
