# Generated by Django 2.2.6 on 2021-04-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_gdsgoodremainslevel'),
        ('mnf', '0007_auto_20191129_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mnfmaterial',
            name='id_good',
        ),
        migrations.AddField(
            model_name='mnfitemdet',
            name='id_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц'),
        ),
        migrations.AddField(
            model_name='mnfshiftresultmaterials',
            name='id_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц'),
        ),
        migrations.AlterUniqueTogether(
            name='mnfitemdet',
            unique_together={('id_item', 'id_good')},
        ),
        migrations.AlterUniqueTogether(
            name='mnfshiftresultmaterials',
            unique_together={('id_shift_result', 'id_good')},
        ),
        migrations.DeleteModel(
            name='MnfMaterialRemainsLevel',
        ),
        migrations.DeleteModel(
            name='MnfRemainsLevel',
        ),
        migrations.RemoveField(
            model_name='mnfitemdet',
            name='id_material',
        ),
        migrations.RemoveField(
            model_name='mnfshiftresultmaterials',
            name='id_material',
        ),
        migrations.DeleteModel(
            name='MnfMaterial',
        ),
    ]
