# Generated by Django 2.2.6 on 2021-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_gdsgoodremainslevel'),
        ('mnf', '0008_auto_20210417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnfitem',
            name='id_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц'),
        ),
    ]
