# Generated by Django 2.2.6 on 2021-04-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stkact_s_desc'),
        ('mnf', '0009_mnfitem_id_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnfshiftresult',
            name='id_act_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.StkAct', verbose_name='Приходная накладная'),
        ),
        migrations.AlterField(
            model_name='mnfitem',
            name='id_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.GdsGood', verbose_name='Тмц'),
        ),
        migrations.AlterField(
            model_name='mnfshiftresult',
            name='id_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.StkAct', verbose_name='Расходная накладная'),
        ),
    ]
