# Generated by Django 2.2.6 on 2019-10-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GdsGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCaption', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'ordering': ['sCaption'],
            },
        ),
    ]
