# Generated by Django 2.2.6 on 2019-11-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdsgood',
            options={'ordering': ['sCaption'], 'verbose_name': 'ТМЦ', 'verbose_name_plural': 'ТМЦ'},
        ),
    ]
