# Generated by Django 2.2.6 on 2021-04-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0001_initial'),
        ('goods', '0002_auto_20191104_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='GdsGoodRemainsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество от')),
                ('n_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='до')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cor.CorColor', verbose_name='Цвет')),
                ('id_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GdsGood', verbose_name='ТМЦ')),
            ],
            options={
                'verbose_name': 'Уровень остатков тмц',
                'verbose_name_plural': 'Уровни остатков тмц',
                'unique_together': {('id_good', 'id_color')},
            },
        ),
    ]
