# Generated by Django 2.2.6 on 2021-04-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0001_initial'),
        ('trd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrdOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_caption', models.CharField(max_length=256, verbose_name='Наименование')),
                ('n_order', models.IntegerField(verbose_name='Порядковый номер состояния')),
            ],
            options={
                'verbose_name': 'Состояние заказа',
                'verbose_name_plural': 'Состояния заказа',
            },
        ),
        migrations.CreateModel(
            name='TrdOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_create_date', models.DateTimeField(verbose_name='Дата содания')),
                ('d_reg_date', models.DateTimeField(db_index=True, verbose_name='Дата регистрации')),
                ('s_desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trd.TrdOrderState', verbose_name='Состояние')),
                ('id_trade_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trd.TrdTradeSystem', verbose_name='Торговая система')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['d_reg_date'],
            },
        ),
        migrations.CreateModel(
            name='TrdOrderStateLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней от')),
                ('n_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='до')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cor.CorColor', verbose_name='Цвет')),
                ('id_order_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trd.TrdOrderState', verbose_name='Состояние заказа')),
                ('id_trade_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trd.TrdTradeSystem', verbose_name='Торговая система')),
            ],
            options={
                'verbose_name': 'Уровень состояния заказа',
                'verbose_name_plural': 'Уровни состояния заказа',
                'ordering': ['id_trade_system', 'id_order_state'],
                'unique_together': {('id_order_state', 'id_trade_system', 'id_color')},
            },
        ),
    ]
