# Generated by Django 2.2.6 on 2021-04-25 14:45

from django.db import migrations

from trd.order.orderModels import TrdOrderState


class Migration(migrations.Migration):
    def install_order_states(apps, schema_editor):
        trdOrderStateClass = apps.get_model('trd', 'TrdOrderState')

        curr_state_dict = {}

        for state in trdOrderStateClass.objects.all():
            curr_state_dict[state.n_order] = 1

        state_dict = {
            100: 'Оформляется', 200: 'Сборка', 300: 'Собран', 400: 'Отправлен', 500: 'Доставлен'
        }

        for n_order in state_dict:
            if n_order not in curr_state_dict:
                state = trdOrderStateClass()
                state.n_order = n_order
                state.s_caption = state_dict[n_order]

    dependencies = [
        ('trd', '0003_auto_20210425_1945'),
    ]

    operations = [
        migrations.RunPython(install_order_states),
    ]
