# Generated by Django 2.2.6 on 2021-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trd', '0005_auto_20210427_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trdorderstatehistory',
            name='id_state_from',
            field=models.BigIntegerField(null=True, verbose_name='Состояние из'),
        ),
    ]
