# Generated by Django 2.2.6 on 2021-04-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0001_initial'),
        ('trd', '0007_auto_20210428_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrdOrderPriorityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cor.CorColor', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Уровень приоритета заказа',
                'verbose_name_plural': 'Уровени приоритета заказа',
            },
        ),
        migrations.CreateModel(
            name='TrdOrderStatePriorityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней от')),
                ('n_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='до')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trd.TrdOrderPriorityLevel', verbose_name='Уровень')),
                ('id_order_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trd.TrdOrderState', verbose_name='Состояние заказа')),
                ('id_trade_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trd.TrdTradeSystem', verbose_name='Торговая система')),
            ],
            options={
                'verbose_name': 'Уровень состояния заказа',
                'verbose_name_plural': 'Уровни состояния заказа',
                'ordering': ['id_trade_system', 'id_order_state'],
                'unique_together': {('id_order_state', 'id_trade_system', 'id_level')},
            },
        ),
        migrations.DeleteModel(
            name='TrdOrderStateLevel',
        ),
    ]
