# Generated by Django 2.2.6 on 2021-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trd', '0008_auto_20210429_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trdorder',
            name='s_reg_num',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Номер'),
        ),
    ]
