# Generated by Django 2.2.6 on 2021-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_caption', models.CharField(max_length=200, verbose_name='Наименование')),
                ('s_color', models.CharField(max_length=200, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
                'ordering': ['s_caption'],
            },
        ),
    ]
